# Generated by Django 5.2.5 on 2025-09-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('book', models.FileField(upload_to='book/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('english', 'English'), ('russian', 'Russian'), ('arabic', 'Arabic'), ('turkish', 'Turkish')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('word_1', models.CharField(max_length=150)),
                ('word_uz', models.CharField(max_length=150)),
                ('text_1', models.TextField()),
                ('text_uz', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='vocab.language')),
            ],
        ),
    ]
