# Generated by Django 5.2.5 on 2025-09-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='vocab',
        ),
        migrations.AddField(
            model_name='vocab',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='vocab.language'),
            preserve_default=False,
        ),
    ]
