# Generated by Django 5.2.5 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='text',
            new_name='text_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default=1, upload_to='book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocab',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='vocab/audio'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='text_uz',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
