# Generated by Django 5.2.5 on 2025-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_rename_text_vocab_text_1_remove_book_link_book_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('english', 'English'), ('russian', 'Russian'), ('arabic', 'Arabic'), ('turkish', 'Turkish')], max_length=100),
        ),
    ]
