# Generated by Django 5.2.5 on 2025-08-13 10:45

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location_district',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='location_region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.district'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.region'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
