# Generated by Django 5.2.5 on 2025-09-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.language'),
        ),
    ]
