# Generated by Django 5.2.5 on 2025-09-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='do',
            name='book',
        ),
        migrations.RemoveField(
            model_name='do',
            name='language',
        ),
        migrations.AddField(
            model_name='task',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.book'),
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.language'),
        ),
    ]
