# Generated by Django 5.2.5 on 2025-09-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='do',
            name='language',
        ),
    ]
